"""Add training metrics and generated_at

Revision ID: 415a5017edce
Revises: 9a88d0b3fe7e
Create Date: 2026-03-16 12:27:08.037228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '415a5017edce'
down_revision: Union[str, Sequence[str], None] = '9a88d0b3fe7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fgi_daily_open_time'), table_name='fgi_daily')
    op.create_index(op.f('ix_fgi_daily_open_time'), 'fgi_daily', ['open_time'], unique=False)
    op.drop_index(op.f('ix_macro_daily_open_time'), table_name='macro_daily')
    op.create_index(op.f('ix_macro_daily_open_time'), 'macro_daily', ['open_time'], unique=False)
    op.create_unique_constraint('uq_macro_daily_open_time', 'macro_daily', ['open_time'])
    op.drop_index(op.f('ix_markets_symbol'), table_name='markets')
    op.create_index(op.f('ix_markets_symbol'), 'markets', ['symbol'], unique=False)
    op.add_column('model_artifacts', sa.Column('training_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('model_artifacts', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('predictions', sa.Column('generated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_predictions_generated_at'), 'predictions', ['generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_generated_at'), table_name='predictions')
    op.drop_column('predictions', 'generated_at')
    op.drop_column('model_artifacts', 'metrics')
    op.drop_column('model_artifacts', 'training_params')
    op.drop_index(op.f('ix_markets_symbol'), table_name='markets')
    op.create_index(op.f('ix_markets_symbol'), 'markets', ['symbol'], unique=True)
    op.drop_constraint('uq_macro_daily_open_time', 'macro_daily', type_='unique')
    op.drop_index(op.f('ix_macro_daily_open_time'), table_name='macro_daily')
    op.create_index(op.f('ix_macro_daily_open_time'), 'macro_daily', ['open_time'], unique=True)
    op.drop_index(op.f('ix_fgi_daily_open_time'), table_name='fgi_daily')
    op.create_index(op.f('ix_fgi_daily_open_time'), 'fgi_daily', ['open_time'], unique=True)
    # ### end Alembic commands ###
