"""Add features and macro tables

Revision ID: 9a88d0b3fe7e
Revises: 2dbea70e6d61
Create Date: 2026-03-16 12:23:20.184756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a88d0b3fe7e'
down_revision: Union[str, Sequence[str], None] = '2dbea70e6d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sp500', sa.Float(), nullable=True),
    sa.Column('log_ret_sp500', sa.Float(), nullable=True),
    sa.Column('vol_7d_sp500', sa.Float(), nullable=True),
    sa.Column('dxy', sa.Float(), nullable=True),
    sa.Column('log_ret_dxy', sa.Float(), nullable=True),
    sa.Column('vol_7d_dxy', sa.Float(), nullable=True),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('log_ret_vix', sa.Float(), nullable=True),
    sa.Column('vol_7d_vix', sa.Float(), nullable=True),
    sa.Column('gold', sa.Float(), nullable=True),
    sa.Column('log_ret_gold', sa.Float(), nullable=True),
    sa.Column('vol_7d_gold', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_daily_id'), 'macro_daily', ['id'], unique=False)
    op.create_index(op.f('ix_macro_daily_open_time'), 'macro_daily', ['open_time'], unique=True)
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('feature_set', sa.String(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'interval', 'open_time', 'feature_set', name='uq_feature_market_interval_time_set')
    )
    op.create_index(op.f('ix_features_feature_set'), 'features', ['feature_set'], unique=False)
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_index(op.f('ix_features_interval'), 'features', ['interval'], unique=False)
    op.create_index(op.f('ix_features_market_id'), 'features', ['market_id'], unique=False)
    op.create_index(op.f('ix_features_open_time'), 'features', ['open_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_open_time'), table_name='features')
    op.drop_index(op.f('ix_features_market_id'), table_name='features')
    op.drop_index(op.f('ix_features_interval'), table_name='features')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_index(op.f('ix_features_feature_set'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_macro_daily_open_time'), table_name='macro_daily')
    op.drop_index(op.f('ix_macro_daily_id'), table_name='macro_daily')
    op.drop_table('macro_daily')
    # ### end Alembic commands ###
