"""Initial migration

Revision ID: e7e0b6fa31d1
Revises: 
Create Date: 2026-03-16 02:24:28.578164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7e0b6fa31d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_id'), 'exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_exchanges_name'), 'exchanges', ['name'], unique=True)
    op.create_table('model_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trained_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('data_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('data_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('feature_set', sa.String(), nullable=False),
    sa.Column('window_size_days', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_artifacts_id'), 'model_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_model_artifacts_is_active'), 'model_artifacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_artifacts_name'), 'model_artifacts', ['name'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('split', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'split', 'metric', name='uq_model_metric')
    )
    op.create_index(op.f('ix_model_metrics_id'), 'model_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_model_metrics_model_id'), 'model_metrics', ['model_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quote_asset', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'asset_id', 'quote_asset', name='uq_symbol_exchange_asset_quote')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.CheckConstraint('high >= GREATEST(open, close)', name='check_high_max'),
    sa.CheckConstraint('low <= LEAST(open, close)', name='check_low_min'),
    sa.CheckConstraint('volume >= 0', name='check_volume_positive'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'interval', 'open_time', name='uq_candle_symbol_interval_time')
    )
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_index(op.f('ix_candles_interval'), 'candles', ['interval'], unique=False)
    op.create_index(op.f('ix_candles_open_time'), 'candles', ['open_time'], unique=False)
    op.create_index(op.f('ix_candles_symbol_id'), 'candles', ['symbol_id'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('feature_set', sa.String(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'interval', 'open_time', 'feature_set', name='uq_feature_symbol_interval_time_set')
    )
    op.create_index(op.f('ix_features_feature_set'), 'features', ['feature_set'], unique=False)
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_index(op.f('ix_features_interval'), 'features', ['interval'], unique=False)
    op.create_index(op.f('ix_features_open_time'), 'features', ['open_time'], unique=False)
    op.create_index(op.f('ix_features_symbol_id'), 'features', ['symbol_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('as_of_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('target_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('pred_open', sa.Float(), nullable=False),
    sa.Column('pred_high', sa.Float(), nullable=False),
    sa.Column('pred_low', sa.Float(), nullable=False),
    sa.Column('pred_close', sa.Float(), nullable=False),
    sa.Column('pred_volume', sa.Float(), nullable=False),
    sa.Column('pred_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_artifacts.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'symbol_id', 'as_of_time', 'target_time', name='uq_prediction')
    )
    op.create_index(op.f('ix_predictions_as_of_time'), 'predictions', ['as_of_time'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_model_id'), 'predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_predictions_symbol_id'), 'predictions', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_predictions_target_time'), 'predictions', ['target_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_target_time'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_symbol_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_as_of_time'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_features_symbol_id'), table_name='features')
    op.drop_index(op.f('ix_features_open_time'), table_name='features')
    op.drop_index(op.f('ix_features_interval'), table_name='features')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_index(op.f('ix_features_feature_set'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_candles_symbol_id'), table_name='candles')
    op.drop_index(op.f('ix_candles_open_time'), table_name='candles')
    op.drop_index(op.f('ix_candles_interval'), table_name='candles')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_model_metrics_model_id'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_model_artifacts_name'), table_name='model_artifacts')
    op.drop_index(op.f('ix_model_artifacts_is_active'), table_name='model_artifacts')
    op.drop_index(op.f('ix_model_artifacts_id'), table_name='model_artifacts')
    op.drop_table('model_artifacts')
    op.drop_index(op.f('ix_exchanges_name'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_id'), table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
